### ISSUE TITLE
Correction needed to "SD Boot mode steps"

### ISSUE THREAD

**Issue by shaunclimbon** [Xilinx/vck190-ethernet-trd#2]
Correction needed here:

- https://xilinx.github.io/vck190-ethernet-trd/build/html/docs/platform/docs/app_deployment.html#sd-boot-mode-steps

That step states "power on the board in SD boot mode".  But I found  the clock settings will be lost if the board is re-powered and Linux will consequently fail to boot.  To avoid this a POR can be used instead.

**Comment by nithinkumark94** [comment]
Hi @mkycrb 
Sorry for the delayed response.
Clock settings can be made non-volatile by using the Set Boot frequency option in the boardUI tool and the latest system controller images.
Else, as you mentioned, even POR can be used.
