### ISSUE TITLE
Instructions for VCK190-ES?

### ISSUE THREAD

**Issue by ksstms** [Xilinx/vck190-ethernet-trd#3]
Hi!
I'm trying to run this TRD on the VCK190-ES board. I modified the project's target device and was able to build it and boot PetaLinux successfully. 

I have set the frequencies as described in the documentation, but got the following messages on boot:
```
[    2.536291] xilinx_axienet a4010000.mrmac: GT lane: 0
[    2.541415] xilinx_axienet a4010000.mrmac: missing/invalid xlnx,addrwidth property, using default
[    2.550439] xilinx_axienet a4010000.mrmac: couldn't find phy i/f
[    2.556825] xilinx_axienet a4011000.mrmac: GT lane: 1
[    2.561936] xilinx_axienet a4011000.mrmac: missing/invalid xlnx,addrwidth property, using default
[    2.570954] xilinx_axienet a4011000.mrmac: couldn't find phy i/f
[    2.577275] xilinx_axienet a4012000.mrmac: GT lane: 2
[    2.582391] xilinx_axienet a4012000.mrmac: missing/invalid xlnx,addrwidth property, using default
[    2.591409] xilinx_axienet a4012000.mrmac: couldn't find phy i/f
[    2.597715] xilinx_axienet a4013000.mrmac: GT lane: 3
[    2.602825] xilinx_axienet a4013000.mrmac: missing/invalid xlnx,addrwidth property, using default
[    2.611836] xilinx_axienet a4013000.mrmac: couldn't find phy i/f
[   11.678036] xilinx_axienet a4010000.mrmac eth0: MRMAC block lock not complete! Cross-check the MAC ref clock configuration
[   11.689091] xilinx_axienet a4010000.mrmac: request_irq() failed
```
I checked some clock frequencies. The RX_REC_CLK output (CLK1 input of the 8A3400) is not running. The transceiver's "usr2" clocks are running at around 342-348 MHz (which should be 322 MHz if I'm not mistaken). 
I couldn't find the cause of this. My board is connected to a 10G switch using a QSFP to 4xSFP breakout cable.

[On the forums](https://support.xilinx.com/s/question/0D52E00006nZ1zySAC/i-have-a-question-about-vck190-ethernet-trd-httpsgithubcomxilinxvck190ethernettrd-?language=en_US) _banjo2002jp_ wrote that he could only get it to work with some specific BoardUI and system controller image version on the production version of the board. I'm using `Board_Framework_Phase1Beta_V1.02_wVadj.img` and BoardUI 1.4 from the early access site.

**Comment by nithinkumark94** [comment]
Hi @ksstms 
Sorry for the delayed response. 
Please find the latest Board UI and system controller images information in this page- https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/973078551/BEAM+Tool+for+VCK190+Evaluation+Kit

**Comment by ksstms** [comment]
Hi @nithinkumark94 
In the [forum thread that linked in my post](https://support.xilinx.com/s/question/0D52E00006nZ1zySAC/i-have-a-question-about-vck190-ethernet-trd-httpsgithubcomxilinxvck190ethernettrd-?language=en_US) they said that the publicly available images are only for the production version of the board. A user pointed out that they have problems even on the production board, as the on-boot clock configuration does not work as intended.

Edit: Please reopen the issue, as my problem is not solved at all.

**Comment by nithinkumark94** [comment]
Hi @ksstms 
I see that one of our employees is discussing with you on the same in the support link and has requested for some information from you.
Request you to respond to his queries so that we can see how to proceed further.

**Comment by ksstms** [comment]
The last answer in the thread is mine, so I'm waiting for a response.

**Comment by ksstms** [comment]
This was solved in the [forum thread](https://support.xilinx.com/s/question/0D52E00006nZ1zySAC/i-have-a-question-about-vck190-ethernet-trd-httpsgithubcomxilinxvck190ethernettrd-?language=en_US).

### Summary:

Version 2021.1 of this TRD does NOT work. See issue #6 

The working combination for the VCK190-ES:
 - Ethernet TRD 2021.2
 - System controller image from early access site: Board_Framework_Phase1Beta_V1.02_wVadj.img
 - BoardUI from early access site: BoardUI 1.4
 - Clock configuration files from AR 76501 (https://support.xilinx.com/s/article/76501) (set as boot config)
