### ISSUE TITLE
xsa difference problem

### ISSUE THREAD

**Issue by JialinZhong** [Xilinx/vck190-ethernet-trd#5]
Pre-build xsa works fine. We can run linux based on it.

But I tried to make a new project based on vivado 2021.2.1..
After Syn&PR, generated xsa has a different size with the pre-build one.
And we met problem when we tried to build linux on this generated xsa.
We got hint in log as:
Configuring network interfaces... [   8.149554] xilinx_axienet a4010000.mrmac eth0: MRMAC block lock not complete! Cross-check the MAC ref clock configuration
[   8.160604] xilinx_axienet a4010000.mrmac: request_irq() failedConfiguring network interfaces... [   8.149554] xilinx_axienet a4010000.mrmac eth0: MRMAC block lock not complete! Cross-check the MAC ref clock configuration

**Comment by nithinkumark94** [comment]
Hi @JialinZhong 

Can you please provide the following details?

1. This usually happens when the clocks are not programmed properly.
     Did you program the clocks using the board UI?
2. What are the changes that you have done to the new project?
3. Does the linux boot completely (even with the error log that you are seeing) or does it hang when booting?

**Comment by JialinZhong** [comment]
> 

1. Board UI was working correctly.
    As I have said that pre-build xsa works fine.
    So the flow is the same on the generated xsa.

2. I think there's totally no change for the new project.
    Every step followed the main.tcl and config.tcl was executed without any error.

3. It booted completely without hanging.

**Comment by ksstms** [comment]
@JialinZhong I'm struggling with the same problem on our VCK190-ES board right now (issue #3). It looks like there are some BoardUI problems even on the production version. [This forum thread](https://support.xilinx.com/s/question/0D52E00006nZ1zySAC/i-have-a-question-about-vck190-ethernet-trd-httpsgithubcomxilinxvck190ethernettrd-?language=en_US) might help you.

**Comment by JialinZhong** [comment]
@ksstms

Many Thanks

We are using VCK190 board with this issue, not the ES board.
The syscon image and Board UI are both the latest.
Because they do work with pre-built xsa, but not work with generated xsa.
So this is not the cause.

**Comment by nithinkumark94** [comment]
Hi @JialinZhong 
Request you to create a support case for the same on xilinx.com.
The issue can be tracked there with the help of our Technical Support folks.

**Comment by JialinZhong** [comment]
@nithinkumark94 
Yes, I have created one on both official website and the forum.
No solution given till now, they gave a reference as you gave above and it does not work.

**Comment by nithinkumark94** [comment]
Hi @JialinZhong 
Please provide the support case number here and close the issue on github.
The issue can now be tracked in the support case.

**Comment by JialinZhong** [comment]
Hi @nithinkumark94 
https://support.xilinx.com/s/question/0D72E000007B3FiSAK/detail?s1oid=00D2E000000nHq7&s1nid=0DB2E000000XdtH&emkind=chatterCommentNotification&s1uid=0052E00000NCvEv&emtm=1647863412163&fromEmail=1&s1ext=0

case link is here, sorry cannot find the number.

**Comment by nithinkumark94** [comment]
Thanks @JialinZhong 
I will close the issue here.
The issue can be being tracked in the support case.

**Comment by elango0301** [comment]
xilinx_axienet 44a00000.ethernet: IRQ index 0 not found
xilinx_axienet 44a00000.ethernet: Ethernet core IRQ not defined
xilinx_axienet 44a00000.ethernet: couldn't find phy i/f
NET: Registered protocol family 17
Key type encrypted registered
Warning: unable to open an initial console.
Freeing unused kernel memory: 168K
This architecture does not have kernel memory protection.
Run /init as init process
/dev/root: Can't open blockdev
/dev/root: Can't open blockdev
random: dd: uninitialized urandom read (512 bytes read)
xilinx_axienet 44a00000.ethernet eth0: XXV MAC block lock not complete! Cross-check the MAC ref clock configuration 


facing this error while testing 10g in virtex ultrascale+
