### ISSUE TITLE
No RX_REC_CLK output in 2021.1 version

### ISSUE THREAD

**Issue by ksstms** [Xilinx/vck190-ethernet-trd#6]
In the 2021.1 version, the `GT_WRAPPER/gt_recovered_clk_bufg_gt_0` buffer's `BUFG_GT_CE` input is not connected.

![image](https://user-images.githubusercontent.com/33523110/159475980-1cb78bb3-e981-4bd0-9808-499e0ffe8a77.png)

This causes it to get optimized in implementation, so the `RX_REC_CLK_out_p/n_0` output gets tied to 0.

![Selection_367](https://user-images.githubusercontent.com/33523110/159474928-9d3bc39f-405e-4e52-9f71-d031a196d119.png)

When you try to boot this up, you get the problems that I described in issue #3. 

The issue isn't present in the 2021.2 version, as the `gt_recovered_clk_bufg_gt_0` was removed, and `hsclk0_rxrecclkout0` is directly connected to `mrmac_obuf_ds_gte5_0`.

**Comment by nithinkumark94** [comment]
Hi @ksstms 
Request you to create a support case for the same on xilinx.com.
The issue can be tracked there with the help of our Technical Support team.

**Comment by juneedshaik** [comment]
Hi @ksstms
Request you to create a support case for the same on xilinx.com.
The issue can be tracked there with the help of our Technical Support team.
